<script setup lang="ts">
import { nextTick,onBeforeUnmount,onMounted,ref,watch } from 'vue'
import { APIError } from '../../api/client'
import { useSessionStore } from '../../stores/session'
import QuestionAttachmentUploader from './QuestionAttachmentUploader.vue'
import QuestionTimeline from './QuestionTimeline.vue'
import TeacherNotePanel from './TeacherNotePanel.vue'
import { changeQuestionStatus,getAdminQuestion,newAdminIdempotencyKey,replyToQuestion,type AdminQuestionDetail,type TeacherNote } from './adminApi'
import type { AttachmentInput,QuestionMessage,QuestionStatus } from './types'
const props=withDefaults(defineProps<{questionId:string;studentLabel?:string}>(),{studentLabel:''});const session=useSessionStore()
const detail=ref<AdminQuestionDetail>(),loading=ref(false),paging=ref(false),error=ref(''),requestId=ref(''),reply=ref(''),attachments=ref<AttachmentInput[]>([]),uploadsPending=ref(false),pending=ref(false),errorBox=ref<HTMLElement>(),back=ref<HTMLAnchorElement>(),uploaderKey=ref(0)
let generation=0,controller:AbortController|undefined,pagingController:AbortController|undefined,mutationController:AbortController|undefined,mutationKey='',mutationFingerprint=''
const labels:Record<QuestionStatus,string>={pending:'待处理',in_progress:'处理中',waiting_student:'等待学生回复',completed:'已完成'}
function active(token:number,id:string){return token===generation&&id===props.questionId}
async function load(){controller?.abort();pagingController?.abort();const token=++generation,id=props.questionId,c=new AbortController();controller=c;loading.value=true;error.value='';requestId.value='';try{const result=await getAdminQuestion(id,{limit:100},c.signal);if(active(token,id))detail.value=result}catch(cause){if(active(token,id)&&!c.signal.aborted)showError(cause)}finally{if(active(token,id))loading.value=false}}
async function loadMore(){if(!detail.value?.nextMessageCursor||paging.value)return;const token=generation,id=props.questionId,cursor=detail.value.nextMessageCursor,c=new AbortController();pagingController?.abort();pagingController=c;paging.value=true;try{const page=await getAdminQuestion(id,{cursor,limit:100},c.signal);if(!active(token,id)||c.signal.aborted||!detail.value)return;const seen=new Set(detail.value.messages.map(message=>message.id));detail.value={...detail.value,messages:[...detail.value.messages,...page.messages.filter(message=>!seen.has(message.id))],nextMessageCursor:page.nextMessageCursor}}catch(cause){if(active(token,id)&&!c.signal.aborted)showError(cause)}finally{if(active(token,id))paging.value=false;if(pagingController===c)pagingController=undefined}}
function showError(cause:unknown){error.value=cause instanceof APIError&&(cause.code==='thread_conflict'||cause.code==='invalid_status_transition')?'问题已变化，请重新加载后再操作':cause instanceof Error?cause.message:'请求失败';requestId.value=cause instanceof APIError?cause.requestId:'';void nextTick(()=>errorBox.value?.focus())}
function merge(messages:QuestionMessage[],message:QuestionMessage){return messages.some(x=>x.id===message.id)?messages:messages.concat(message)}
async function sendReply(){if(!detail.value||pending.value||uploadsPending.value)return;const value=reply.value.trim();if(!value)return;const id=props.questionId,token=generation,fingerprint=JSON.stringify([id,value,attachments.value,detail.value.thread.version]);if(mutationFingerprint!==fingerprint){mutationFingerprint=fingerprint;mutationKey=newAdminIdempotencyKey()}const c=new AbortController();mutationController=c;pending.value=true;error.value='';try{const result=await replyToQuestion(id,value,attachments.value,mutationKey,detail.value.thread.version,c.signal);if(!active(token,id)||!detail.value)return;detail.value={...detail.value,thread:result.thread,messages:merge(detail.value.messages,result.message)};reply.value='';attachments.value=[];mutationKey='';mutationFingerprint='';uploaderKey.value+=1}catch(cause){if(active(token,id)&&!c.signal.aborted)showError(cause)}finally{if(active(token,id))pending.value=false;if(mutationController===c)mutationController=undefined}}
async function setStatus(status:QuestionStatus){if(!detail.value||pending.value)return;const student=props.studentLabel?`${props.studentLabel}（${detail.value.thread.studentId}）`:detail.value.thread.studentId,action=status==='completed'?'标记为已完成':detail.value.thread.status==='pending'?'领取':'重新打开';if(!confirm(`确认将 ${student} 的问题「${detail.value.thread.title}」${action}吗？`))return;const id=props.questionId,token=generation,c=new AbortController();mutationController=c;pending.value=true;error.value='';try{const thread=await changeQuestionStatus(id,status,detail.value.thread.version,c.signal);if(active(token,id)&&detail.value)detail.value={...detail.value,thread}}catch(cause){if(active(token,id)&&!c.signal.aborted)showError(cause)}finally{if(active(token,id))pending.value=false;if(mutationController===c)mutationController=undefined}}
function addNote(note:TeacherNote){if(detail.value&&!detail.value.notes.some(x=>x.id===note.id))detail.value={...detail.value,notes:[...detail.value.notes,note]}}
function reset(){generation+=1;controller?.abort();pagingController?.abort();mutationController?.abort();mutationController=undefined;detail.value=undefined;reply.value='';attachments.value=[];uploadsPending.value=false;pending.value=false;paging.value=false;error.value='';requestId.value='';mutationKey='';mutationFingerprint='';uploaderKey.value+=1;void load();void nextTick(()=>back.value?.focus())}
onMounted(()=>{void load();void nextTick(()=>back.value?.focus())});watch(()=>props.questionId,reset);onBeforeUnmount(()=>{generation+=1;controller?.abort();pagingController?.abort();mutationController?.abort()})
</script>
<template><section class="teacher-detail"><RouterLink custom to="/admin/questions" v-slot="{href,navigate}"><a ref="back" class="back" :href="href" @click="navigate">← 返回问题队列</a></RouterLink><p v-if="loading">正在加载问题…</p><p v-if="error" ref="errorBox" role="alert" tabindex="-1">{{error}}<span v-if="requestId">（支持编号：{{requestId}}）</span> <button data-testid="retry-detail" type="button" @click="load">重新加载</button></p><template v-if="detail"><header><div><p>{{studentLabel||detail.thread.studentId}}</p><h1>{{detail.thread.title}}</h1><span class="badge">{{labels[detail.thread.status]}}</span></div><div><button v-if="detail.thread.status==='pending'" data-testid="claim" :disabled="pending" @click="setStatus('in_progress')">领取问题</button><button v-if="detail.thread.status!=='completed'" data-testid="complete" :disabled="pending" @click="setStatus('completed')">标记完成</button><button v-else data-testid="reopen" :disabled="pending" @click="setStatus('in_progress')">重新打开</button></div></header><div data-testid="timeline"><QuestionTimeline viewer-role="admin" :messages="detail.messages" /></div><button v-if="detail.nextMessageCursor" data-testid="more-messages" :disabled="paging" @click="loadMore">{{paging?'加载中…':'加载更多消息'}}</button><form data-testid="reply-form" @submit.prevent="sendReply"><h2>回复学生</h2><label>回复内容<textarea v-model="reply" maxlength="20000" required /></label><QuestionAttachmentUploader :key="uploaderKey" role="admin" :user-id="session.user?.id||''" :disabled="pending" @update:attachments="attachments=$event" @pending-change="uploadsPending=$event"/><button type="button" :disabled="pending||uploadsPending" @click="sendReply">{{pending?'提交中…':'发送回复'}}</button></form><TeacherNotePanel :question-id="questionId" :notes="detail.notes" @added="addNote"/></template></section></template>
<style scoped>.teacher-detail{display:grid;gap:18px;min-width:0}.teacher-detail>header{display:flex;justify-content:space-between;gap:12px}.teacher-detail>header>div:last-child{display:flex;gap:8px;align-items:start}.badge{display:inline-block;padding:4px 9px;border-radius:20px;background:var(--hl-primary-soft);color:var(--hl-primary-strong)}.teacher-detail form{display:grid;gap:10px;padding:16px;border:1px solid var(--hl-border);border-radius:10px;background:var(--hl-surface-solid)}.teacher-detail label{display:grid;gap:6px}.teacher-detail textarea{min-height:110px;background:var(--hl-surface-solid);color:var(--hl-text)}.back{display:none}@media(max-width:900px){.back{display:inline-block}.teacher-detail>header{flex-direction:column}}</style>
