import { flushPromises, mount } from '@vue/test-utils'
import { describe, expect, it, vi } from 'vitest'
import { APIError } from '../../api/client'
import { createPinia } from 'pinia'
const api=vi.hoisted(()=>({get:vi.fn(),reply:vi.fn(),status:vi.fn(),key:vi.fn(()=> 'key-1')}))
vi.mock('./adminApi',async(original)=>({...(await original<typeof import('./adminApi')>()),getAdminQuestion:api.get,replyToQuestion:api.reply,changeQuestionStatus:api.status,newAdminIdempotencyKey:api.key}))
vi.mock('./QuestionAttachmentUploader.vue',()=>({default:{template:'<div data-uploader />'}}))
vi.mock('./TeacherQuestionListView.vue',()=>({default:{template:'<div data-teacher-list />'}}))
import TeacherQuestionDetailView from './TeacherQuestionDetailView.vue'
const detail={thread:{id:'q1',studentId:'s1',title:'二次函数',status:'in_progress',version:2,lastMessageAt:'2026-01-01',createdAt:'2026-01-01',updatedAt:'2026-01-01'},messages:[{id:'m1',senderRole:'student',kind:'initial',body:'public question',createdAt:'2026-01-01',attachments:[]}],notes:[{id:'n1',authorUserId:'a1',body:'secret note',createdAt:'2026-01-01'}]}
const options={props:{questionId:'q1',studentLabel:'林同学'},global:{plugins:[createPinia()],stubs:{RouterLink:{template:'<a><slot/></a>'}}}}
describe('TeacherQuestionDetailView',()=>{
  it('keeps notes outside the public timeline DOM and supports canonical reply result',async()=>{api.get.mockResolvedValue(detail);api.reply.mockResolvedValue({thread:{...detail.thread,version:3},message:{id:'m2',senderRole:'admin',kind:'admin_reply',body:'answer',createdAt:'now',attachments:[]}});const w=mount(TeacherQuestionDetailView,options);await flushPromises();expect(w.get('[data-testid="timeline"]').text()).not.toContain('secret note');await w.get('[data-testid="reply-form"] textarea').setValue('answer');await w.get('[data-testid="reply-form"]').trigger('submit');await flushPromises();expect(api.reply).toHaveBeenCalledWith('q1','answer',[],'key-1',2,expect.any(AbortSignal));expect(w.get('[data-testid="timeline"]').text()).toContain('answer')})
  it('preserves a failed payload key and gives a reload action for version conflicts',async()=>{api.get.mockResolvedValue(detail);api.reply.mockRejectedValue(new APIError(409,'thread_conflict','conflict','req-c'));const w=mount(TeacherQuestionDetailView,options);await flushPromises();await w.get('[data-testid="reply-form"] textarea').setValue('answer');await w.get('[data-testid="reply-form"]').trigger('submit');await flushPromises();await w.get('[data-testid="reply-form"]').trigger('submit');await flushPromises();expect(api.reply.mock.calls[0][3]).toBe(api.reply.mock.calls[1][3]);expect(w.text()).toContain('重新加载');expect(w.text()).toContain('req-c')})
  it('reuses a key after a response-lost failure and rotates it after success or editing',async()=>{api.key.mockReset().mockReturnValueOnce('key-a').mockReturnValueOnce('key-b');api.get.mockResolvedValue(detail);api.reply.mockRejectedValueOnce(new APIError(0,'network_error','lost','')).mockResolvedValueOnce({thread:{...detail.thread,version:3},message:{id:'m2',senderRole:'admin',kind:'admin_reply',body:'answer',createdAt:'now',attachments:[]}}).mockResolvedValueOnce({thread:{...detail.thread,version:4},message:{id:'m3',senderRole:'admin',kind:'admin_reply',body:'edited',createdAt:'now',attachments:[]}});const w=mount(TeacherQuestionDetailView,options);await flushPromises();const form=w.get('[data-testid="reply-form"]');await form.get('textarea').setValue('answer');await form.trigger('submit');await flushPromises();await form.trigger('submit');await flushPromises();await form.get('textarea').setValue('edited');await form.trigger('submit');await flushPromises();const calls=api.reply.mock.calls.slice(-3);expect(calls.map(call=>call[3])).toEqual(['key-a','key-a','key-b'])})
  it('confirms status changes with student and title but no message/note text',async()=>{api.get.mockResolvedValue(detail);api.status.mockResolvedValue({...detail.thread,status:'completed',version:3});const confirm=vi.fn((_message:string)=>true);vi.stubGlobal('confirm',confirm);const w=mount(TeacherQuestionDetailView,options);await flushPromises();await w.get('[data-testid="complete"]').trigger('click');await flushPromises();expect(confirm).toHaveBeenCalledWith(expect.stringContaining('林同学'));expect(confirm.mock.calls[0][0]).toContain('二次函数');expect(confirm.mock.calls[0][0]).not.toContain('public question');expect(confirm.mock.calls[0][0]).not.toContain('secret note')})
  it('aborts an in-flight mutation when the route selection changes',async()=>{let resolveReply!:(value:unknown)=>void;api.get.mockImplementation((id:string)=>Promise.resolve({...detail,thread:{...detail.thread,id}}));api.reply.mockImplementation(()=>new Promise(resolve=>{resolveReply=resolve}));const w=mount(TeacherQuestionDetailView,options);await flushPromises();await w.get('[data-testid="reply-form"] textarea').setValue('answer');await w.get('[data-testid="reply-form"]').trigger('submit');const call=api.reply.mock.calls[api.reply.mock.calls.length-1] as unknown[];const signal=call[5] as AbortSignal;await w.setProps({questionId:'q2'});await flushPromises();expect(signal.aborted).toBe(true);resolveReply({thread:{...detail.thread,id:'q1'},message:{id:'stale'}});await flushPromises();expect(w.text()).not.toContain('stale')})
  it('aborts and ignores a late status result after selection changes',async()=>{let resolveStatus!:(value:unknown)=>void;api.get.mockImplementation((id:string)=>Promise.resolve({...detail,thread:{...detail.thread,id}}));api.status.mockImplementation(()=>new Promise(resolve=>{resolveStatus=resolve}));vi.stubGlobal('confirm',vi.fn((_message:string)=>true));const w=mount(TeacherQuestionDetailView,options);await flushPromises();await w.get('[data-testid="complete"]').trigger('click');const call=api.status.mock.calls[api.status.mock.calls.length-1] as unknown[];const signal=call[3] as AbortSignal;await w.setProps({questionId:'q2'});await flushPromises();expect(signal.aborted).toBe(true);resolveStatus({...detail.thread,id:'q1',status:'completed'});await flushPromises();expect(w.text()).toContain('处理中');expect(w.text()).not.toContain('已完成')})
})
