import { flushPromises, mount } from '@vue/test-utils'
import { beforeEach,describe, expect, it, vi } from 'vitest'
import { APIError } from '../../api/client'
import { createPinia } from 'pinia'
import { createMemoryHistory,createRouter } from 'vue-router'
const api=vi.hoisted(()=>({get:vi.fn(),reply:vi.fn(),status:vi.fn(),key:vi.fn(()=> 'key-1')}))
vi.mock('./adminApi',async(original)=>({...(await original<typeof import('./adminApi')>()),getAdminQuestion:api.get,replyToQuestion:api.reply,changeQuestionStatus:api.status,newAdminIdempotencyKey:api.key}))
vi.mock('./QuestionAttachmentUploader.vue',()=>({default:{template:'<div data-uploader />'}}))
vi.mock('./TeacherQuestionListView.vue',()=>({default:{template:'<div data-teacher-list />'}}))
import TeacherQuestionDetailView from './TeacherQuestionDetailView.vue'
const detail={thread:{id:'q1',studentId:'s1',title:'二次函数',status:'in_progress',version:2,lastMessageAt:'2026-01-01',createdAt:'2026-01-01',updatedAt:'2026-01-01'},messages:[{id:'m1',senderRole:'student',kind:'initial',body:'public question',createdAt:'2026-01-01',attachments:[]}],notes:[{id:'n1',authorUserId:'a1',body:'secret note',createdAt:'2026-01-01'}]}
const options={props:{questionId:'q1',studentLabel:'林同学'},global:{plugins:[createPinia()],stubs:{RouterLink:{template:'<a><slot/></a>'}}}}
describe('TeacherQuestionDetailView',()=>{
  beforeEach(()=>{api.get.mockReset();api.reply.mockReset();api.status.mockReset();api.key.mockReset().mockReturnValue('key-1')})
  it('keeps notes outside the public timeline DOM and supports canonical reply result',async()=>{api.get.mockResolvedValue(detail);api.reply.mockResolvedValue({thread:{...detail.thread,version:3},message:{id:'m2',senderRole:'admin',kind:'admin_reply',body:'answer',createdAt:'now',attachments:[]}});const w=mount(TeacherQuestionDetailView,options);await flushPromises();expect(w.get('[data-testid="timeline"]').text()).not.toContain('secret note');await w.get('[data-testid="reply-form"] textarea').setValue('answer');await w.get('[data-testid="reply-form"]').trigger('submit');await flushPromises();expect(api.reply).toHaveBeenCalledWith('q1','answer',[],'key-1',2,expect.any(AbortSignal));expect(w.get('[data-testid="timeline"]').text()).toContain('answer')})
  it('submits a reply when the visible send button is clicked',async()=>{api.get.mockResolvedValue(detail);api.reply.mockResolvedValue({thread:{...detail.thread,version:3},message:{id:'m2',senderRole:'admin',kind:'admin_reply',body:'answer',createdAt:'now',attachments:[]}});const w=mount(TeacherQuestionDetailView,options);await flushPromises();await w.get('[data-testid="reply-form"] textarea').setValue('answer');await w.get('[data-testid="reply-form"] button:last-child').trigger('click');await flushPromises();expect(api.reply).toHaveBeenCalledOnce()})
  it('preserves a failed payload key and gives a reload action for version conflicts',async()=>{api.get.mockResolvedValue(detail);api.reply.mockRejectedValue(new APIError(409,'thread_conflict','conflict','req-c'));const w=mount(TeacherQuestionDetailView,options);await flushPromises();await w.get('[data-testid="reply-form"] textarea').setValue('answer');await w.get('[data-testid="reply-form"]').trigger('submit');await flushPromises();await w.get('[data-testid="reply-form"]').trigger('submit');await flushPromises();expect(api.reply.mock.calls[0][3]).toBe(api.reply.mock.calls[1][3]);expect(w.text()).toContain('重新加载');expect(w.text()).toContain('req-c')})
  it('reuses a key after a response-lost failure and rotates it after success or editing',async()=>{api.key.mockReset().mockReturnValueOnce('key-a').mockReturnValueOnce('key-b');api.get.mockResolvedValue(detail);api.reply.mockRejectedValueOnce(new APIError(0,'network_error','lost','')).mockResolvedValueOnce({thread:{...detail.thread,version:3},message:{id:'m2',senderRole:'admin',kind:'admin_reply',body:'answer',createdAt:'now',attachments:[]}}).mockResolvedValueOnce({thread:{...detail.thread,version:4},message:{id:'m3',senderRole:'admin',kind:'admin_reply',body:'edited',createdAt:'now',attachments:[]}});const w=mount(TeacherQuestionDetailView,options);await flushPromises();const form=w.get('[data-testid="reply-form"]');await form.get('textarea').setValue('answer');await form.trigger('submit');await flushPromises();await form.trigger('submit');await flushPromises();await form.get('textarea').setValue('edited');await form.trigger('submit');await flushPromises();const calls=api.reply.mock.calls.slice(-3);expect(calls.map(call=>call[3])).toEqual(['key-a','key-a','key-b'])})
  it('confirms status changes with student and title but no message/note text',async()=>{api.get.mockResolvedValue(detail);api.status.mockResolvedValue({...detail.thread,status:'completed',version:3});const confirm=vi.fn((_message:string)=>true);vi.stubGlobal('confirm',confirm);const w=mount(TeacherQuestionDetailView,options);await flushPromises();await w.get('[data-testid="complete"]').trigger('click');await flushPromises();expect(confirm).toHaveBeenCalledWith(expect.stringContaining('林同学'));expect(confirm.mock.calls[0][0]).toContain('s1');expect(confirm.mock.calls[0][0]).toContain('二次函数');expect(confirm.mock.calls[0][0]).not.toContain('public question');expect(confirm.mock.calls[0][0]).not.toContain('secret note')})
  it('aborts an in-flight mutation when the route selection changes',async()=>{let resolveReply!:(value:unknown)=>void;api.get.mockImplementation((id:string)=>Promise.resolve({...detail,thread:{...detail.thread,id}}));api.reply.mockImplementation(()=>new Promise(resolve=>{resolveReply=resolve}));const w=mount(TeacherQuestionDetailView,options);await flushPromises();await w.get('[data-testid="reply-form"] textarea').setValue('answer');await w.get('[data-testid="reply-form"]').trigger('submit');const call=api.reply.mock.calls[api.reply.mock.calls.length-1] as unknown[];const signal=call[5] as AbortSignal;await w.setProps({questionId:'q2'});await flushPromises();expect(signal.aborted).toBe(true);resolveReply({thread:{...detail.thread,id:'q1'},message:{id:'stale'}});await flushPromises();expect(w.text()).not.toContain('stale')})
  it('aborts and ignores a late status result after selection changes',async()=>{let resolveStatus!:(value:unknown)=>void;api.get.mockImplementation((id:string)=>Promise.resolve({...detail,thread:{...detail.thread,id}}));api.status.mockImplementation(()=>new Promise(resolve=>{resolveStatus=resolve}));vi.stubGlobal('confirm',vi.fn((_message:string)=>true));const w=mount(TeacherQuestionDetailView,options);await flushPromises();await w.get('[data-testid="complete"]').trigger('click');const call=api.status.mock.calls[api.status.mock.calls.length-1] as unknown[];const signal=call[3] as AbortSignal;await w.setProps({questionId:'q2'});await flushPromises();expect(signal.aborted).toBe(true);resolveStatus({...detail.thread,id:'q1',status:'completed'});await flushPromises();expect(w.text()).toContain('处理中');expect(w.text()).not.toContain('已完成')})
  it('lets a teacher claim pending work using expectedVersion',async()=>{api.get.mockResolvedValue({...detail,thread:{...detail.thread,status:'pending',version:7}});api.status.mockResolvedValue({...detail.thread,status:'in_progress',version:8});vi.stubGlobal('confirm',vi.fn((_message:string)=>true));const w=mount(TeacherQuestionDetailView,options);await flushPromises();await w.get('[data-testid="claim"]').trigger('click');await flushPromises();expect(api.status).toHaveBeenCalledWith('q1','in_progress',7,expect.any(AbortSignal))})
  it('pages 101+ messages with cursor, deduplicates IDs and ignores a late page',async()=>{let resolvePage!:(value:unknown)=>void;api.get.mockResolvedValueOnce({...detail,nextMessageCursor:'cursor-1'}).mockImplementationOnce(()=>new Promise(resolve=>{resolvePage=resolve})).mockResolvedValueOnce({...detail,thread:{...detail.thread,id:'q2'},messages:[]});const w=mount(TeacherQuestionDetailView,options);await flushPromises();await w.get('[data-testid="more-messages"]').trigger('click');const call=api.get.mock.calls[1] as unknown[];expect(call[1]).toEqual({cursor:'cursor-1',limit:100});const signal=call[2] as AbortSignal;await w.setProps({questionId:'q2'});await flushPromises();expect(signal.aborted).toBe(true);resolvePage({...detail,messages:[detail.messages[0],{...detail.messages[0],id:'m101',body:'late page'}]});await flushPromises();expect(w.text()).not.toContain('late page')})
  it('merges a second conceptual 101+ page by ID and advances its cursor',async()=>{const first=Array.from({length:100},(_,index)=>({...detail.messages[0],id:`m${index}`,body:`message ${index}`,createdAt:`2026-01-01T00:${String(index%60).padStart(2,'0')}:00Z`}));api.get.mockResolvedValueOnce({...detail,messages:first,nextMessageCursor:'cursor-1'}).mockResolvedValueOnce({...detail,messages:[first[99],{...detail.messages[0],id:'m100',body:'message 100',createdAt:'2026-01-02'}]});const w=mount(TeacherQuestionDetailView,options);await flushPromises();await w.get('[data-testid="more-messages"]').trigger('click');await flushPromises();expect(w.findAll('[data-testid="timeline"] article')).toHaveLength(101);expect(w.find('[data-testid="more-messages"]').exists()).toBe(false)})
  it('shows retry and request id when the initial detail fails',async()=>{api.get.mockRejectedValueOnce(new APIError(500,'internal_error','加载失败','req-detail')).mockResolvedValueOnce(detail);const w=mount(TeacherQuestionDetailView,options);await flushPromises();expect(w.get('[role="alert"]').text()).toContain('req-detail');await w.get('[data-testid="retry-detail"]').trigger('click');await flushPromises();expect(w.text()).toContain('二次函数')})
  it('focuses a real keyboard-activatable mobile back anchor',async()=>{api.get.mockResolvedValue(detail);const router=createRouter({history:createMemoryHistory(),routes:[{path:'/admin/questions',component:{template:'<p>list</p>'}},{path:'/admin/questions/:questionId',component:{template:'<p>detail</p>'}}]});await router.push('/admin/questions/q1');await router.isReady();const w=mount(TeacherQuestionDetailView,{attachTo:document.body,props:{questionId:'q1'},global:{plugins:[createPinia(),router]}});await flushPromises();const anchor=w.get('a.back');expect(anchor.attributes('href')).toBe('/admin/questions');expect(anchor.attributes('tabindex')).toBeUndefined();expect(document.activeElement).toBe(anchor.element);w.unmount()})
})
