<script setup lang="ts">
import {onBeforeUnmount,onMounted,ref,watch} from 'vue'
import {APIError} from '../../api/client'
import {listAdminQuestions,type AdminQuestionThread} from './adminApi'
import type {QuestionStatus} from './types'
const items=ref<AdminQuestionThread[]>([]),status=ref<QuestionStatus|''>(''),studentId=ref(''),from=ref(''),to=ref(''),nextCursor=ref<string>(),loading=ref(false),error=ref(''),requestId=ref('');let generation=0,controller:AbortController|undefined
const labels:Record<QuestionStatus,string>={pending:'待处理',in_progress:'处理中',waiting_student:'等待学生回复',completed:'已完成'}
function utc(value:string){return value?new Date(`${value}T00:00:00Z`).toISOString().replace('.000Z','Z'):undefined}
async function load(cursor?:string){controller?.abort();const c=new AbortController(),token=++generation;controller=c;loading.value=true;error.value='';requestId.value='';try{const page=await listAdminQuestions({status:status.value||undefined,studentId:studentId.value.trim()||undefined,from:utc(from.value),to:utc(to.value),limit:20},cursor,c.signal);if(token!==generation)return;items.value=cursor?[...items.value,...page.items]:page.items;nextCursor.value=page.nextCursor}catch(cause){if(token===generation&&!c.signal.aborted){error.value=cause instanceof Error?cause.message:'加载失败';requestId.value=cause instanceof APIError?cause.requestId:''}}finally{if(token===generation)loading.value=false}}
let timer:number|undefined;function schedule(){window.clearTimeout(timer);timer=window.setTimeout(()=>void load(),120)}
watch([status,studentId,from,to],schedule);onMounted(()=>void load());onBeforeUnmount(()=>{generation+=1;controller?.abort();window.clearTimeout(timer)})
</script>
<template><section class="teacher-queue" aria-labelledby="teacher-questions-title"><header><p>老师答疑</p><h1 id="teacher-questions-title">问题队列</h1></header><form class="filters" @submit.prevent="load()"><label>状态<select v-model="status"><option value="">全部</option><option v-for="(label,key) in labels" :key="key" :value="key">{{label}}</option></select></label><label>学生 ID<input v-model="studentId" placeholder="UUID" /></label><label>开始日期<input v-model="from" type="date" /></label><label>结束日期<input v-model="to" type="date" /></label></form><p v-if="error" role="alert">{{error}}<span v-if="requestId">（支持编号：{{requestId}}）</span></p><p v-if="loading&&!items.length">正在加载队列…</p><p v-else-if="!items.length">暂无问题</p><ul v-else><li v-for="thread in items" :key="thread.id"><RouterLink :to="`/admin/questions/${encodeURIComponent(thread.id)}`"><strong>{{thread.title}}</strong><span>{{labels[thread.status]}}</span><small>学生 {{thread.studentId}}</small><time :datetime="thread.lastMessageAt">{{new Date(thread.lastMessageAt).toLocaleString('zh-CN')}}</time></RouterLink></li></ul><button v-if="nextCursor" :disabled="loading" @click="load(nextCursor)">加载更多</button></section></template>
<style scoped>.teacher-queue{display:grid;gap:16px;max-width:1000px}.filters{display:grid;grid-template-columns:repeat(4,minmax(140px,1fr));gap:10px}.filters label{display:grid;gap:5px}.filters input,.filters select{padding:8px}.teacher-queue ul{display:grid;gap:9px;padding:0;list-style:none}.teacher-queue li a{display:grid;grid-template-columns:1fr auto;gap:7px;padding:15px;border:1px solid #dbe4f0;border-radius:10px;background:#fff;color:#182842;text-decoration:none}.teacher-queue small,.teacher-queue time{color:#617086}@media(max-width:900px){.filters{grid-template-columns:1fr 1fr}}@media(max-width:560px){.filters{grid-template-columns:1fr}.teacher-queue li a{grid-template-columns:1fr}}</style>
