<script setup lang="ts">
import { onBeforeMount, onBeforeUnmount, ref } from 'vue'
import { recentLessons } from '../learning/api'
import type { RecentLesson } from '../learning/types'
const recent = ref<RecentLesson[]>([])
let controller: AbortController | undefined
onBeforeMount(async()=>{controller=new AbortController();try{recent.value=await recentLessons(controller.signal)}catch{/* Home remains useful when recent lessons are unavailable. */}})
onBeforeUnmount(()=>controller?.abort())
</script>
<template>
  <section class="home" aria-labelledby="student-home-title">
    <header class="home-header"><div><p class="eyebrow"><span aria-hidden="true"></span> 学习首页</p><h1 id="student-home-title">把每一步想清楚</h1><p class="lead">这里将陪你梳理高中数学和物理中的关键问题，让练习更有方向。</p></div><div class="subject-chip" aria-label="学习科目：数学与物理"><span class="subject-icon" aria-hidden="true">▤</span><span><small>当前方向</small><strong>数学 · 物理</strong></span></div></header>
    <div class="dashboard-grid">
      <article class="next-step">
        <div class="card-kicker"><span>今日学习提示</span><span class="card-icon" aria-hidden="true">✦</span></div>
        <h2>从错题的第一步重新推导</h2><p>保持好奇，认真写下每一个已知条件和推理过程。</p>
        <div class="thinking-steps" aria-label="学习步骤"><span><b>1</b>读清题意</span><i aria-hidden="true"></i><span><b>2</b>独立推导</span><i aria-hidden="true"></i><span><b>3</b>回看复盘</span></div>
        <RouterLink class="start" to="/student/learning"><span>开始学习课程</span><span class="link-arrow" aria-hidden="true">›</span></RouterLink>
      </article>
      <aside class="quick-panel" aria-label="学习快捷入口"><p>快捷入口</p><RouterLink to="/student/learning"><span class="shortcut-icon" aria-hidden="true">▤</span><span><strong>课程学习</strong><small>继续你的学习进度</small></span><span class="arrow" aria-hidden="true">›</span></RouterLink><RouterLink to="/student/questions"><span class="shortcut-icon" aria-hidden="true">?</span><span><strong>答疑中心</strong><small>把卡住的问题弄明白</small></span><span class="arrow" aria-hidden="true">›</span></RouterLink></aside>
    </div>
    <section v-if="recent.length" class="recent" aria-labelledby="recent-title"><div class="section-heading"><div><p>学习轨迹</p><h2 id="recent-title">最近学习</h2></div><RouterLink to="/student/learning">查看全部</RouterLink></div><div class="recent-list"><RouterLink v-for="item in recent" :key="item.revisionId" :to="`/student/learning/${encodeURIComponent(item.lessonId)}`"><span class="recent-icon" aria-hidden="true">▤</span><span class="recent-copy"><strong>{{ item.title }}</strong><span>上次阅读到 {{ Math.round(item.position.scrollRatio*100) }}%</span></span><span class="progress" aria-hidden="true"><i :style="{ width: `${Math.round(item.position.scrollRatio*100)}%` }"></i></span><span class="recent-arrow" aria-hidden="true">›</span></RouterLink></div></section>
  </section>
</template>
<style scoped>
.home{width:min(100%,1180px);margin:0 auto}.home-header{display:flex;align-items:flex-start;justify-content:space-between;gap:28px;margin-bottom:30px}.eyebrow{display:flex;align-items:center;gap:8px;margin:0;color:var(--hl-primary-strong);font-size:.76rem;font-weight:750;letter-spacing:.12em}.eyebrow span{width:7px;height:7px;border-radius:50%;background:var(--hl-accent);box-shadow:0 0 0 4px var(--hl-primary-soft)}.home h1{margin:.55rem 0 .65rem;font-size:clamp(2rem,4vw,3rem);line-height:1.12;letter-spacing:-.045em}.lead{max-width:650px;margin:0;color:var(--hl-text-muted);font-size:.96rem;line-height:1.75}.subject-chip{display:flex;align-items:center;gap:11px;min-width:176px;padding:12px 15px;border:1px solid var(--hl-border);border-radius:13px;background:var(--hl-surface);box-shadow:var(--hl-shadow-soft)}.subject-icon{display:grid;flex:0 0 23px;place-items:center;width:23px;height:23px;color:var(--hl-primary);font-size:1.2rem;font-weight:750}.subject-chip>span:last-child{display:grid}.subject-chip small{color:var(--hl-text-muted);font-size:.66rem}.subject-chip strong{margin-top:2px;font-size:.8rem}
.dashboard-grid{display:grid;grid-template-columns:minmax(0,1.65fr) minmax(260px,.75fr);gap:20px}.next-step,.quick-panel,.recent{border:1px solid var(--hl-border);border-radius:18px;background:var(--hl-surface-solid);box-shadow:var(--hl-shadow-soft)}.next-step{position:relative;isolation:isolate;overflow:hidden;padding:30px;background:linear-gradient(135deg,var(--hl-surface-solid),color-mix(in srgb,var(--hl-primary-soft) 48%,var(--hl-surface-solid)))}.next-step::after{content:"";position:absolute;z-index:-1;right:-55px;bottom:-75px;width:230px;height:230px;border-radius:50%;background:var(--hl-primary-soft);filter:blur(5px)}.card-kicker{display:flex;align-items:center;justify-content:space-between;color:var(--hl-primary-strong);font-size:.76rem;font-weight:750;letter-spacing:.08em}.card-icon{color:var(--hl-accent);font-size:1.3rem}.next-step h2{max-width:580px;margin:15px 0 9px;font-size:clamp(1.35rem,2.5vw,1.85rem);letter-spacing:-.035em}.next-step>p{max-width:580px;margin:0;color:var(--hl-text-muted);font-size:.9rem;line-height:1.7}.thinking-steps{display:flex;align-items:center;gap:10px;margin-top:25px;color:var(--hl-text-muted);font-size:.72rem}.thinking-steps span{display:flex;align-items:center;gap:6px;white-space:nowrap}.thinking-steps b{display:grid;place-items:center;width:21px;height:21px;border-radius:7px;background:var(--hl-primary-soft);color:var(--hl-primary-strong);font-size:.67rem}.thinking-steps i{width:20px;height:1px;background:var(--hl-border-strong)}.start{display:inline-flex;align-items:center;gap:8px;margin-top:25px;padding:10px 15px;border-radius:9px;background:var(--hl-primary);box-shadow:0 8px 20px rgba(13,148,136,.2);color:#fff;text-decoration:none;font-size:.82rem;font-weight:720;transition:transform .16s ease,box-shadow .16s ease}.start:hover{transform:translateY(-1px);box-shadow:0 11px 24px rgba(13,148,136,.26)}.link-arrow{font-size:1.2rem;line-height:1}
.quick-panel{padding:18px}.quick-panel>p{margin:2px 4px 12px;color:var(--hl-text-muted);font-size:.7rem;font-weight:750;letter-spacing:.1em}.quick-panel>a{display:flex;align-items:center;gap:11px;padding:13px 10px;border-radius:11px;color:var(--hl-text);text-decoration:none;transition:background .16s ease}.quick-panel>a+a{margin-top:4px}.quick-panel>a:hover{background:var(--hl-surface-muted)}.shortcut-icon{display:grid;flex:0 0 39px;place-items:center;width:39px;height:39px;border-radius:11px;background:var(--hl-primary-soft);color:var(--hl-primary-strong);font-size:1.05rem;font-weight:750}.quick-panel a>span:nth-child(2){display:grid;min-width:0}.quick-panel strong{font-size:.82rem}.quick-panel small{margin-top:3px;color:var(--hl-text-muted);font-size:.68rem}.arrow{margin-left:auto;color:var(--hl-text-soft);font-size:1.2rem;line-height:1}
.recent{margin-top:20px;padding:23px}.section-heading{display:flex;align-items:end;justify-content:space-between;margin-bottom:15px}.section-heading p{margin:0 0 4px;color:var(--hl-primary-strong);font-size:.67rem;font-weight:750;letter-spacing:.1em}.section-heading h2{margin:0;font-size:1.08rem}.section-heading>a{color:var(--hl-primary-strong);font-size:.74rem;font-weight:650;text-decoration:none}.recent-list{display:grid;gap:8px}.recent-list>a{display:flex;align-items:center;gap:12px;padding:12px;border:1px solid transparent;border-radius:11px;color:var(--hl-text);text-decoration:none;transition:border-color .16s ease,background .16s ease}.recent-list>a:hover{border-color:var(--hl-border);background:var(--hl-surface-muted)}.recent-icon{display:grid;flex:0 0 36px;place-items:center;width:36px;height:36px;border-radius:10px;background:var(--hl-surface-muted);color:var(--hl-primary);font-size:1rem;font-weight:750}.recent-copy{display:grid;min-width:160px}.recent-copy strong{overflow:hidden;font-size:.8rem;text-overflow:ellipsis;white-space:nowrap}.recent-copy>span{margin-top:3px;color:var(--hl-text-muted);font-size:.68rem}.progress{flex:1;height:5px;overflow:hidden;border-radius:99px;background:var(--hl-bg-deep)}.progress i{display:block;height:100%;border-radius:inherit;background:linear-gradient(90deg,var(--hl-primary),var(--hl-accent))}.recent-arrow{color:var(--hl-text-soft);font-size:1.2rem;line-height:1}
@media(max-width:850px){.home-header{display:block}.subject-chip{display:none}.dashboard-grid{grid-template-columns:1fr}.quick-panel{display:grid;grid-template-columns:1fr 1fr;gap:8px}.quick-panel>p{grid-column:1/-1}.quick-panel>a+a{margin-top:0}}
@media(max-width:560px){.home-header{margin-bottom:23px}.lead{font-size:.9rem}.next-step{padding:23px 20px}.thinking-steps{gap:6px}.thinking-steps i{width:8px}.thinking-steps span{font-size:.66rem}.quick-panel{grid-template-columns:1fr}.quick-panel>p{grid-column:auto}.recent{padding:18px 13px}.progress{display:none}.recent-copy{min-width:0;flex:1}}
</style>
