#!/usr/bin/env bash
# shellcheck disable=SC2016
set -Eeuo pipefail
IFS=$'\n\t'
umask 077

fail() { printf 'phase6 release matrix adapter: FAIL: %s\n' "$1" >&2; exit 1; }
portable_mode() {
  if stat -c '%a' -- "$1" >/dev/null 2>&1; then stat -c '%a' -- "$1"; else stat -f '%Lp' -- "$1"; fi
}
portable_owner() {
  if stat -c '%u' -- "$1" >/dev/null 2>&1; then stat -c '%u' -- "$1"; else stat -f '%u' -- "$1"; fi
}

[[ $# == 4 ]] || fail 'invalid arguments'
stage=$1
case_name=$2
expected=$3
matrix_root=$4
[[ $stage =~ ^[a-z_]+$ && $case_name =~ ^[a-z][a-z0-9_]{0,63}$ &&
  $expected =~ ^[a-z][a-z0-9_]{0,63}$ ]] || fail 'invalid matrix identity'
[[ $matrix_root == /* && -d $matrix_root && ! -L $matrix_root &&
  $(portable_mode "$matrix_root") == 700 &&
  $(portable_owner "$matrix_root") == "$(id -u)" ]] || fail 'unsafe matrix root'
context=$matrix_root/context.env
[[ -f $context && ! -L $context && $(portable_mode "$context") == 600 &&
  $(portable_owner "$context") == "$(id -u)" ]] || fail 'unsafe matrix context'
# The context is generated by e2e-phase6.sh from validated, run-unique values.
# shellcheck disable=SC1090
source "$context"

for variable in REPO_ROOT HARNESS_TMPDIR RELEASE_PROJECT MAIN_ENV MANIFEST_A \
  MANIFEST_B STATE_DIR SECRET_DIR RUNNER_IMAGE COMPOSE_PROJECT OWNER_LABEL \
  OWNER_TOKEN DOMAIN; do
  [[ -n ${!variable:-} ]] || fail "missing context $variable"
done
for path in "$REPO_ROOT" "$HARNESS_TMPDIR" "$RELEASE_PROJECT" "$STATE_DIR" "$SECRET_DIR"; do
  [[ $path == /* && -d $path && ! -L $path ]] || fail 'invalid context directory'
done
for path in "$MAIN_ENV" "$MANIFEST_A" "$MANIFEST_B"; do
  [[ $path == /* && -f $path && ! -L $path ]] || fail 'invalid context file'
done
[[ $RELEASE_PROJECT == "$HARNESS_TMPDIR"/* && $STATE_DIR == "$HARNESS_TMPDIR"/* &&
  $SECRET_DIR == "$HARNESS_TMPDIR"/* && $MAIN_ENV == "$HARNESS_TMPDIR"/* &&
  $MANIFEST_A == "$HARNESS_TMPDIR"/* && $MANIFEST_B == "$HARNESS_TMPDIR"/* ]] ||
  fail 'context escapes disposable root'
[[ $COMPOSE_PROJECT =~ ^happylearn_phase6_[a-f0-9]{12}_prod$ &&
  $OWNER_TOKEN =~ ^[a-f0-9]{12}$ && $DOMAIN =~ ^phase6-[a-f0-9]{12}\.test$ &&
  $RUNNER_IMAGE =~ ^[A-Za-z0-9._/:@-]+$ ]] || fail 'invalid context value'

case_root=$matrix_root/cases/$case_name
snapshot=$case_root/snapshot.json
baseline_schema_file=$case_root/baseline-schema
release_log=$case_root/release.log

root_exec() {
  docker run --rm --interactive --network none --memory 512m --cpus .5 \
    --label "$OWNER_LABEL=$OWNER_TOKEN" \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$REPO_ROOT:$REPO_ROOT:ro" \
    --volume "$HARNESS_TMPDIR:$HARNESS_TMPDIR" \
    --workdir "$REPO_ROOT" --env "HAPPYLEARN_LOCAL_COMPOSE_PROJECT=$COMPOSE_PROJECT" \
    --entrypoint /bin/bash "$RUNNER_IMAGE" "$@"
}

root_exec_low_disk() {
  docker run --rm --interactive --network none --memory 512m --cpus .5 \
    --label "$OWNER_LABEL=$OWNER_TOKEN" \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$REPO_ROOT:$REPO_ROOT:ro" \
    --volume "$HARNESS_TMPDIR:$HARNESS_TMPDIR" \
    --tmpfs /matrix-low-disk:rw,noexec,nosuid,nodev,size=4m,uid=10003,gid=0,mode=0700 \
    --workdir "$REPO_ROOT" --env "HAPPYLEARN_LOCAL_COMPOSE_PROJECT=$COMPOSE_PROJECT" \
    --entrypoint /bin/bash "$RUNNER_IMAGE" "$@"
}

compose() {
  local environment=$1
  shift
  root_exec -eu -c '
    repository=$1; environment=$2; shift 2
    exec timeout --foreground --kill-after=10s 360s docker compose \
      --project-name "$HAPPYLEARN_LOCAL_COMPOSE_PROJECT" \
      --project-directory "$repository" --env-file "$environment" \
      -f "$repository/deploy/compose.prod.yml" \
      -f "$repository/deploy/compose.prod.local.yml" "$@"
  ' _ "$RELEASE_PROJECT" "$environment" "$@"
}

activate_environment() {
  local manifest=$1
  root_exec -eu -c '
    environment=$1; manifest=$2
    temporary=$(mktemp --tmpdir="$(dirname "$environment")" .matrix-env.XXXXXX)
    grep -Ev "^HAPPYLEARN_(APP|WORKER|MIGRATE|BACKUP|CADDY|POSTGRES|REDIS|MINIO)_IMAGE=" "$environment" >"$temporary"
    for mapping in APP:app WORKER:worker MIGRATE:migrate BACKUP:backup CADDY:caddy POSTGRES:postgres REDIS:redis MINIO:minio; do
      variable=${mapping%%:*}; key=${mapping#*:}
      value=$(jq -er --arg key "$key" ".images[\$key]" "$manifest")
      printf "HAPPYLEARN_%s_IMAGE=%s\n" "$variable" "$value" >>"$temporary"
    done
    install -o 0 -g 0 -m 0600 "$temporary" "$environment"
    rm -f -- "$temporary"
  ' _ "$MAIN_ENV" "$manifest"
}

refresh_recovery() {
  local manifest=$1
  root_exec -eu -c '
    evidence=$(jq -er .backupEvidenceId "$1")
    body=$(jq -cn --arg evidence "$evidence" --arg now "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
      "{status:\"verified\",evidenceId:\$evidence,verifiedAt:\$now}")
    printf "%s\n" "$body" >"$2/recovery/latest.json"
    chown 0:0 "$2/recovery/latest.json"; chmod 0600 "$2/recovery/latest.json"
  ' _ "$manifest" "$STATE_DIR"
}

state_value() {
  local expression=$1 fallback=${2:-none}
  root_exec -eu -c 'if [[ -f $1 && ! -L $1 ]]; then jq -er "$2" "$1" 2>/dev/null || printf "%s\n" "$3"; else printf "%s\n" "$3"; fi' \
    _ "$STATE_DIR/release-state.json" "$expression" "$fallback"
}

database_mode() {
  compose "$MAIN_ENV" exec -T postgres psql --username happylearn --dbname happylearn \
    --no-psqlrc --quiet --tuples-only --no-align --set ON_ERROR_STOP=1 \
    --command 'SELECT mode FROM operational_modes WHERE singleton_id=true;' | tr -d '[:space:]'
}

database_schema() {
  compose "$MAIN_ENV" exec -T postgres psql --username happylearn --dbname happylearn \
    --no-psqlrc --quiet --tuples-only --no-align --set ON_ERROR_STOP=1 \
    --command 'SELECT COALESCE(MAX(version_id),0) FROM goose_db_version WHERE is_applied;' | tr -d '[:space:]'
}

edge_status() {
  compose "$MAIN_ENV" exec -T caddy sh -eu -c '
    curl --insecure --silent --output /dev/null --write-out "%{http_code}\n" \
      --connect-timeout 3 --max-time 10 --resolve "$1:443:127.0.0.1" \
      "https://$1/api/v1/health/live"
  ' _ "$DOMAIN"
}

manifest_hash() {
  root_exec -eu -c 'if [[ -f $1 && ! -L $1 ]]; then sha256sum "$1" | awk "{print \$1}"; else printf "none\n"; fi' _ "$1"
}

reset_baseline() {
  activate_environment "$MANIFEST_A"
  root_exec -eu -c '
    state=$1; active=$2; candidate=$3
    rm -f -- "$state/release-state.json" "$state/previous-manifest.json" \
      "$state/failed-manifest.json" "$state/rollback.env" \
      "$state/rollback-diagnostics.json"
    install -o 0 -g 0 -m 0600 "$active" "$state/active-manifest.json"
    install -o 10001 -g 10001 -m 0600 "$candidate" \
      "$state/release-input/candidate-manifest.json"
  ' _ "$STATE_DIR" "$MANIFEST_A" "$MANIFEST_B"
  compose "$MAIN_ENV" --profile release stop --timeout 10 release-control >/dev/null 2>&1 || true
  compose "$MAIN_ENV" up --detach --no-deps app worker caddy >/dev/null
  compose "$MAIN_ENV" exec -T caddy caddy reload --config /etc/caddy/Caddyfile --adapter caddyfile >/dev/null
  local deadline=$((SECONDS + 180)) mode status
  while :; do
    mode=$(database_mode 2>/dev/null || true)
    status=$(edge_status 2>/dev/null || true)
    [[ $mode == normal && $status == 200 ]] && break
    ((SECONDS < deadline)) || fail 'baseline did not return to normal traffic'
    sleep 2
  done
  refresh_recovery "$MANIFEST_B"
}

write_snapshot() {
  local current_state result failure mode traffic active_hash schema recovery rollback_diagnostics
  current_state=$(state_value '.state // "none"')
  result=$(state_value '.result // "none"')
  failure=$(state_value '.rollbackFailureCategory // "none"')
  mode=$(database_mode)
  traffic=$(edge_status)
  active_hash=$(manifest_hash "$STATE_DIR/active-manifest.json")
  schema=$(database_schema)
  recovery=$(root_exec -eu -c 'jq -er ".status" "$1/recovery/latest.json"' _ "$STATE_DIR")
  rollback_diagnostics=false
  root_exec -eu -c '[[ ! -f $1 || -L $1 ]]' _ "$STATE_DIR/rollback-diagnostics.json" || rollback_diagnostics=true
  [[ $current_state =~ ^[a-z_]+$ && $result =~ ^[a-z_]+$ &&
    $failure =~ ^[a-z_]+$ && $mode =~ ^[a-z_]+$ &&
    $traffic =~ ^[0-9]{3}$ && $active_hash =~ ^[a-f0-9]{64}$ &&
    $schema =~ ^[0-9]+$ && $recovery == verified ]] || fail 'unsafe live snapshot value'
  jq -cn --arg case "$case_name" --arg expected "$expected" \
    --arg state "$current_state" --arg result "$result" --arg failure "$failure" \
    --arg mode "$mode" --arg traffic "$traffic" --arg active "$active_hash" \
    --arg schema "$schema" --arg recovery "$recovery" \
    --argjson rollbackDiagnostics "$rollback_diagnostics" \
    '{case:$case,expected:$expected,state:$state,result:$result,failureCategory:$failure,operationalMode:$mode,trafficStatus:$traffic,activeManifestSha256:$active,schemaVersion:$schema,recoveryStatus:$recovery,rollbackDiagnostics:$rollbackDiagnostics}' \
    >"$snapshot"
  chmod 0600 "$snapshot"
}

invoke_release() {
  local environment=$1 manifest=$2 injection=${3:-} rollback_injection=${4:-} runner=root_exec
  [[ $case_name != insufficient_disk ]] || runner=root_exec_low_disk
  "$runner" env HAPPYLEARN_RELEASE_FAILURE_INJECTION="$injection" \
    HAPPYLEARN_ROLLBACK_FAILURE_INJECTION="$rollback_injection" \
    "$RELEASE_PROJECT/scripts/prod-release.sh" --project-dir "$RELEASE_PROJECT" \
    --env-file "$environment" --manifest "$manifest" \
    --version "$(root_exec -eu -c 'jq -er .version "$1"' _ "$manifest")" \
    --mode local --confirm-maintenance-window
}

prepare_case() {
  if [[ -e $case_root ]]; then
    [[ -d $case_root && ! -L $case_root && $case_root == "$matrix_root"/cases/* ]] || fail 'unsafe case root'
    find "$case_root" -mindepth 1 -delete
  else
    mkdir -p "$case_root"
  fi
  chmod 0700 "$matrix_root/cases" "$case_root"
  reset_baseline
  database_schema >"$baseline_schema_file"
  chmod 0600 "$baseline_schema_file"
  activate_environment "$MANIFEST_B"
}

prepare_unsafe_secret() {
  local bad_secrets=$case_root/unsafe-secrets bad_env=$case_root/unsafe.env
  root_exec -eu -c '
    cp -a -- "$1" "$2"
    chmod 0644 "$2/postgres-password"
    sed "s|^HAPPYLEARN_SECRET_DIR=.*|HAPPYLEARN_SECRET_DIR=$2|" "$3" >"$4"
    chown 0:0 "$4"; chmod 0600 "$4"
  ' _ "$SECRET_DIR" "$bad_secrets" "$MAIN_ENV" "$bad_env"
  printf '%s\n' "$bad_env"
}

prepare_insufficient_disk() {
  local low_env=$case_root/low-disk.env
  root_exec -eu -c '
    sed "s|^HAPPYLEARN_BACKUP_HOST_PATH=.*|HAPPYLEARN_BACKUP_HOST_PATH=/matrix-low-disk|" "$1" >"$2"
    chown 0:0 "$2"; chmod 0600 "$2"
  ' _ "$MAIN_ENV" "$low_env"
  printf '%s\n' "$low_env"
}

prepare_unavailable_digest() {
  local bad_env=$case_root/unavailable.env bad_manifest=$case_root/unavailable.json
  local digest
  digest="127.0.0.1:9/happylearn/unavailable@sha256:$(printf 'f%.0s' {1..64})"
  root_exec -eu -c '
    sed "s|^HAPPYLEARN_APP_IMAGE=.*|HAPPYLEARN_APP_IMAGE=$3|" "$1" >"$2"
    jq --arg image "$3" ".images.app=\$image" "$4" >"$5"
    chown 0:0 "$2" "$5"; chmod 0600 "$2" "$5"
  ' _ "$MAIN_ENV" "$bad_env" "$digest" "$MANIFEST_B" "$bad_manifest"
  printf '%s|%s\n' "$bad_env" "$bad_manifest"
}

run_signal_matrix() {
  local signal_state status terminal result
  local -a states=(preflight backup_started backup_verified release_mode maintenance drained images_pulled schema_compatible migrated services_started ready smoke_passed activated normal traffic_open succeeded)
  : >"$case_root/signal-results"
  for signal_state in "${states[@]}"; do
    reset_baseline
    activate_environment "$MANIFEST_B"
    status=0
    invoke_release "$MAIN_ENV" "$MANIFEST_B" "signal:$signal_state" >"$release_log.$signal_state" 2>&1 || status=$?
    ((status != 0)) || fail "signal $signal_state did not interrupt"
    terminal=$(state_value '.state // "none"')
    result=$(state_value '.result // "none"')
    if [[ $terminal != failed_safe && ! ( $terminal == normal && $result == rolled_back ) &&
      ! ( $terminal == succeeded && $result == succeeded ) ]]; then
      invoke_release "$MAIN_ENV" "$MANIFEST_B" >"$case_root/resume.$signal_state.log" 2>&1 ||
        fail "signal $signal_state was neither resumable nor failed safe"
      terminal=$(state_value '.state // "none"')
      result=$(state_value '.result // "none"')
    fi
    if [[ $terminal == failed_safe && $result == failed ]]; then
      printf '%s|failed_safe\n' "$signal_state" >>"$case_root/signal-results"
    elif [[ $terminal == normal && $result == rolled_back ]]; then
      printf '%s|rolled_back\n' "$signal_state" >>"$case_root/signal-results"
    elif [[ $terminal == succeeded && $result == succeeded ]]; then
      printf '%s|resumed\n' "$signal_state" >>"$case_root/signal-results"
    else
      fail "unsafe signal terminal state $signal_state"
    fi
  done
  [[ $(wc -l <"$case_root/signal-results") == 16 ]] || fail 'incomplete signal matrix'
  reset_baseline
  activate_environment "$MANIFEST_B"
}

inject_case() {
  local environment=$MAIN_ENV manifest=$MANIFEST_B injection='' rollback_injection='' status=0 pair
  case $case_name in
    unsafe_secret) environment=$(prepare_unsafe_secret) ;;
    insufficient_disk) environment=$(prepare_insufficient_disk) ;;
    unavailable_digest)
      pair=$(prepare_unavailable_digest); environment=${pair%%|*}; manifest=${pair#*|} ;;
    pre_release_backup_failure|drain_timeout|migration_lock_conflict|migration_failure|app_readiness_failure|worker_readiness_failure|object_store_restart_failure|smoke_failure)
      injection=$case_name ;;
    previous_image_success) injection=app_readiness_failure ;;
    previous_image_incompatible)
      injection=app_readiness_failure; rollback_injection=previous_image_incompatible ;;
    previous_image_readiness_failure)
      injection=app_readiness_failure; rollback_injection=previous_image_readiness_failure ;;
    signal_each_durable_step)
      run_signal_matrix
      write_snapshot
      return 0 ;;
    *) fail 'unsupported case' ;;
  esac
  invoke_release "$environment" "$manifest" "$injection" "$rollback_injection" >"$release_log" 2>&1 || status=$?
  ((status != 0)) || fail 'injected release unexpectedly succeeded'
  write_snapshot
}

assert_durable_state() {
  [[ -f $snapshot && ! -L $snapshot ]] || fail 'snapshot unavailable'
  case $expected in
    preflight_rejected)
      jq -e '.state=="preflight" and .result=="failed"' "$snapshot" >/dev/null ;;
    pre_maintenance_failed)
      jq -e '.state=="backup_started" and .result=="failed"' "$snapshot" >/dev/null ;;
    previous_image_rolled_back)
      jq -e '.state=="normal" and .result=="rolled_back"' "$snapshot" >/dev/null ;;
    maintenance_failed_safe)
      jq -e '.state=="failed_safe" and .result=="failed"' "$snapshot" >/dev/null ;;
    resumable_or_failed_safe)
      [[ $(wc -l <"$case_root/signal-results") == 16 ]] ;;
    *) return 1 ;;
  esac
  case $case_name in
    previous_image_incompatible)
      jq -e '.failureCategory=="schema_incompatible"' "$snapshot" >/dev/null ;;
    previous_image_readiness_failure)
      jq -e '.failureCategory=="rollback_readiness_failed"' "$snapshot" >/dev/null ;;
  esac
}

assert_maintenance() {
  case $expected in
    maintenance_failed_safe) jq -e '.operationalMode=="release"' "$snapshot" >/dev/null ;;
    *) jq -e '.operationalMode=="normal"' "$snapshot" >/dev/null ;;
  esac
}

assert_traffic() {
  case $expected in
    maintenance_failed_safe) jq -e '.trafficStatus=="503"' "$snapshot" >/dev/null ;;
    *) jq -e '.trafficStatus=="200"' "$snapshot" >/dev/null ;;
  esac
}

assert_manifests() {
  local expected_hash
  expected_hash=$(manifest_hash "$MANIFEST_A")
  jq -e --arg hash "$expected_hash" '.activeManifestSha256==$hash' "$snapshot" >/dev/null
}

assert_schema() {
  local baseline
  baseline=$(<"$baseline_schema_file")
  jq -e --arg schema "$baseline" '.schemaVersion==$schema' "$snapshot" >/dev/null
}

assert_recovery() {
  jq -e '.recoveryStatus=="verified"' "$snapshot" >/dev/null
}

assert_diagnostics() {
  jq -e '
    (keys|sort)==(["activeManifestSha256","case","expected","failureCategory","operationalMode","recoveryStatus","result","rollbackDiagnostics","schemaVersion","state","trafficStatus"]|sort) and
    ([.[]|select(type=="string")|select(test("(?i)(password|credential|bearer|authorization|cookie|object[_ -]?key|database[_ -]?url|redis[_ -]?url)") or test("[\\r\\n]"))]|length)==0
  ' "$snapshot" >/dev/null
  if [[ $expected == previous_image_rolled_back ]]; then
    jq -e '.rollbackDiagnostics==true' "$snapshot" >/dev/null
  fi
}

cleanup_case() {
  reset_baseline
  [[ $(database_mode) == normal && $(edge_status) == 200 ]] || fail 'cleanup did not restore traffic'
  [[ $(manifest_hash "$STATE_DIR/active-manifest.json") == "$(manifest_hash "$MANIFEST_A")" ]] ||
    fail 'cleanup did not restore active manifest'
  printf '%s\n' cleaned >"$case_root/cleanup"
  chmod 0600 "$case_root/cleanup"
}

case $stage in
  prepare) prepare_case ;;
  inject) inject_case ;;
  durable_state) assert_durable_state ;;
  maintenance) assert_maintenance ;;
  traffic) assert_traffic ;;
  manifests) assert_manifests ;;
  schema) assert_schema ;;
  recovery) assert_recovery ;;
  diagnostics) assert_diagnostics ;;
  cleanup) cleanup_case ;;
  *) fail 'invalid stage' ;;
esac
